minio:
  url: http://localhost:9000
  username: minioadmin
  password: minioadmin
  bucketName: test
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.163.com
    username: your-email
    password: your-password
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: spring-boot-film
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/film
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 10
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
